denoland/docland

components/doc.tsx
Add line breaks to the sidebar headers to make them look good.
for example:
- https://doc.deno.land/https://cdn.esm.sh/v58/firebase@9.4.1/database/dist/database/index.d.ts
- https://doc.deno.land/https://github.com/denoland/deno_std/raw/main/http/mod.ts
before:
after:
=> chore: add `break-all` if the title of the header in the sidebar is URL

components/doc.tsx, components/jsdoc_test.tsx, components/types.tsx, components/types_test.tsx, shared.ts, test.ts
Now, a type reference from something like `Deno.connect` to `Deno.Conn` provides a link. Previously, it would not have resolved a link to the type reference.
Fixes #25
=> fix: namespaced type refs resolve

components/common.tsx, components/doc.tsx, components/namespaces.tsx, middleware/badge.ts
Ref #3 
This is part 1 of what I suggested in #3, where namespaces are flattened on the index page, so "all" symbols are listed.
Here is what it looks like for `/deno/stable` now:
And here is what it looks like for `oak`:
=> feat: flatten namespaces on index pages

components/common.tsx, components/specifier_form.tsx
Various minor improvements to the site:
- Form now has validation tags
- Anchors can now not be tabbed to anymore (they weren't visible previously when tabbed to)
- The `Deno Doc` title on the index page is now left aligned with the form
- The buttons on the index page are now not an `a` element enclosing a `button` anymore. Rather it is now just an `a` tag. The `a` + `button` is not semantically correct, and caused incorrect tab navigation behaviour.﻿
=> fix: various improvements

deps.ts
Closes #33
Moving to `https://deno.land/x/deno_doc@v0.22.0/mod.ts` pins the dependency as well as causes a slightly different (more efficient) path to instantiate the WASM module to be used.  Moving back to rawgithub doesn't seem to be able to replicate the issue before, but this version is stable and shouldn't float.  It could have been that having an unpinned raw github caused some sort of problem in Deploy's cache when we made the change, where the WASM was out of sync with the generated JavaScript?
=> chore: update to deno_doc@v0.22.0

components/app.tsx, components/doc.tsx, components/jsdoc_test.tsx, components/specifier_form.tsx, components/styles.ts, deps.ts, shared.ts
Closes #28
An initial responsive design for the doc website.  It differs a bit from `deno.land` in that I _really_ didn't want to use client side JavaScript if I could avoid it, so the top nav hamburger is a CSS only way, and it was easier/better to "expand" out the menu instead of sort of popup.
https://user-images.githubusercontent.com/1282577/145991553-9530f91a-640e-44a4-848f-dabbedb6288d.mp4
=> feat: responsive design

components/jsdoc.tsx, components/jsdoc_test.tsx
Closes #53
This currently includes #58 and needs to be rebased when that is merged.
=> feat: render `@example` JSDoc tags

routes/doc.tsx, test.ts
Closes #38
This follows redirects for the doc module, redirecting the doc URL to the final URL.  So for example currently `https://doc.deno.land/https://deno.land/std/testing/asserts.ts` would get redirected to `https://doc.deno.land/https://deno.land/std@0.119.0/testing/asserts.ts`.
=> feat: follow redirects in doc URLs

components/types.tsx
Fixes: #68
This works around denoland/deno_doc#226 which will also be fixed, but keeps from having to bump versions immediately.
=> fix: correct mapped typed rendering

deps.ts, main.ts, middleware/ga.ts
Closes: #65 
This will require a web property ID to be provisioned in Google Analytics and added to the Deploy config before it would be active.
=> feat: integrate Google Analytics

components/doc.tsx, components/doc_test.tsx, components/meta.tsx, routes/doc.tsx, test.ts, util.ts
This also includes a fix for `skypack.dev` where there was a regression because of the way we now redirect the client to any redirected URLs.
=> feat: improve package info and document title

components/common.tsx, components/jsdoc.tsx, components/jsdoc_test.tsx, components/styles.ts, components/types.tsx
Closes #46
This supports the most "common" `@link` formats, including linking to other symbols in the doc, but it doesn't support the full complement of things supported by closure compiler (which things like the Firebase JSDocs use).  In these cases it just applies some styling to the tag.
=> feat: support JSDoc @info tags

.github/workflows/ci.yml, components/common.tsx, components/doc.tsx, components/doc_test.tsx, components/jsdoc.tsx, deps.ts, deps_test.ts, main.ts, middleware/ga.ts, util.ts, util_test.ts
Closes: #101
This also updates some of the dependencies.
=> feat: provide a usage block in a module documentation

components/doc.tsx, components/doc_test.tsx
Closes: #103
For example, `serveFile` now becomes:
=> feat: add import usage for individual symbols

.github/workflows/ci.yml
`build.ts` is not tested in CI and it was actually found broken while releasing 1.19.3 (#115).
This PR adds a step to ensure it's working in CI and prevents the situation like the above in the future.
=> test: ensure build.ts working in CI

components/doc.tsx, components/doc_test.tsx
With the upgrade to Nano JSX, the refactor of the the button code did not actually set the on click handler.  This fixes that issue.
=> fix: copy button onclick

components/common.tsx, components/indexPage.tsx, components/markdown.tsx
Closes #130
This provides a more concise index page for modules, where the current form, with a complex module, can get difficult to navigate.  This brings it closer to the "package"/folder index page.
**Before**
**After**
It also aligns the "tags" between the module index page and the package index page.
=> feat: restructure module index pages

components/app.tsx, middleware/notFound.tsx
* Fixes footer position making it stick to bottom
* Adjust error message on the not found page
Before: 
After:
=> fix: footer styles, adjust error message on the not found page

components/classes.tsx
=> fix: jsdoc tags for constructors

components/types.tsx, deps.ts, docs.ts, routes/doc.tsx
This add import map auto-detection support for deno.land/x packages.  A follow-up PR will add an import map or config file query parameter for other modules.
=> feat: add import map support for deno.land/x modules

.github/workflows/update_deno.yml
I just ran a test on the CI and got this (I haven't tested this locally because it's kind of CI specific)
```
error: Uncaught (in promise) PermissionDenied: Requires read access to "/home/runner/.deno/bin/git", run again with the --allow-read flag
const result = await Deno.stat(path);
^
at async Object.stat (deno:runtime/js/30_fs.js:230:17)
at async RealEnvironment.fileExists (https://deno.land/x/which@0.2.1/mod.ts:19:22)
at async which (https://deno.land/x/which@0.2.1/mod.ts:66:11)
at async resolveCommand (https://deno.land/x/dax@0.7.0/src/shell.ts:632:23)
at async executeCommandArgs (https://deno.land/x/dax@0.7.0/src/shell.ts:530:25)
at async executeSimpleCommand (https://deno.land/x/dax@0.7.0/src/shell.ts:517:10)
at async executeSequentialList …
```
=> chore: fix permissions on create PR workflow

components/app.tsx
This was deprecated since a while now.
=> chore: remove link to translations

routes/doc.tsx
Should fix broken documentation links for modules with numeric digits in their names. 
Currently only `a-zA-Z_` is permitted in the code, but the registry allows modules with names like https://deno.land/x/911 to be registered.
Thanks!
=> fix: URL regex for deno.land/x modules

docs.ts, middleware/notFound.tsx, routes/doc.tsx
This commit adds a special `User-Agent` header to outbound fetch requests.
Currently the user-agent header that upstream servers see is `Deno/1.40.4` which is a common value across all requests made from deployments on Deno Deploy. Having a special user-agent in docland will help upstreams easily identify requests coming from docland.
=> fix: add user-agent to outbound fetch requests
