components/meta.tsx, deps.ts, main.ts
=> fix: use `Deno.readFile` for static files and add title to landing page

main.ts, middleware/badge.ts, static/badge.svg, test.ts
=> fix: add back badge.svg

middleware/logging.ts, routes/doc.tsx, test.ts
Fixes #1
(and also improves the logging output to make it more usable)
=> fix: merge doc nodes for static libs

routes/doc.tsx, test.ts
=> feat: redirect doc queries to permalink

util.ts, util_test.ts
PR #24 pointed out that there are a couple of other registry patterns we should parse.
=> feat: add more registry patterns

components/interfaces.tsx
Closes https://github.com/denoland/docland/issues/20
=> fix: sort interface members alphabetically

components/common.tsx, components/common_test.tsx
=> fix: improve src links to builtins

components/app.tsx, components/common.tsx, components/common_test.tsx, components/doc.tsx, components/jsdoc.tsx, components/jsdoc_test.tsx, components/specifier_form.tsx, components/styles.ts, deps.ts
Closes #21
https://user-images.githubusercontent.com/1282577/146113421-fec4ac87-1970-4ac5-8f0f-d8e3361a6aad.mp4
=> feat: add dark mode

components/common.tsx, components/doc.tsx, components/doc_test.tsx, components/namespaces.tsx, components/styles.ts
=> fix: handle situations where function nodes are mixed with other doc

main.ts
This commit streams static assets and properly handles 404s.
=> refactor: stream static assets

components/common.tsx, components/common_test.tsx, main.ts, routes/raw.ts
=> feat: integrate doc_proxy

components/jsdoc_test.tsx, components/styles.ts
=> fix: issues with styling JSDoc markdown

deps.ts
This will add the `exception` hit type, so exceptions are reported "properly" as well as fixes the `referer` header.
=> chore: update ga dependency

.github/workflows/ci.yml, deps_test.ts, main.ts, middleware/ga.ts, middleware/ga_test.ts
This will filter out noisy and uninformative URLs from Google Analytics.
=> feat: filter out noisy URLs from ga

deps.ts
Fixes #76 (for real this time!)
=> chore: update to deno_doc 0.26.1 and std 0.121.0

components/app.tsx, main.ts
Closes #110
Lighthouse with this on a "big" page:
=> feat: add minimal service worker

.github/workflows/ci.yml, .vscode/settings.json, build.ts, components/doc.tsx, components/doc_test.tsx, components/jsdoc.tsx, components/jsdoc_test.tsx, deno.jsonc, deps.ts, deps_test.ts, import-map.json, types.d.ts, util.ts
General updates to dependencies and fully migrate to esm.sh which has cleanup a lot of the type "magic" that was needed.
=> refactor: update dependencies and migrate fully to esm.sh

routes/doc.tsx, test.ts
=> fix: properly detect index URLs

components/types.tsx
Co-authored-by: Kitson Kelly <me@kitsonkelly.com>
Closes #128
=> fix: escape strings

components/specifier_form.tsx
cheeky bit of self-marketing ;) 
feel free to just close it if that's not cool!
=> feat: add supabase-js sample

.github/workflows/update_deno.yml, build.ts
This adds a new workflow that we can dispatch which will run `deno task build` then open a PR.
Two commits:
1. First switches to using my new library.
2. Second adds the workflow.
=> chore: workflow for automatically updating files during a release
